name: MoonlyteLobby
version: '${project.version}'
main: moonlyte.moonlyte.MoonlyteLobby
api-version: 1.18
authors: [ Jonas ]
description: Moonlyte lobby plugin
website: moonlyte.io
commands:
  serverSelector:
    description: Select a gamemode
    usage: /<command>